<a href="https://colab.research.google.com/github/cs10101/F1_race_winner_prediction_model/blob/main/F1_model_training_version_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# loading dataset

In [5]:
f1_data = pd.read_csv("f1_master_cleaned.csv")

display(f1_data.head())

display(f1_data.shape)

,season,round,race_name,team,grid_position,driver_code,participated_in_qualifying,reached_q2,reached_q3,model_q1_seconds,model_q2_seconds,model_q3_seconds,best_valid_quali_time,quali_position_numeric,pole_time_seconds,gap_to_pole_pct_model
0,2018,1,Australian Grand Prix,Ferrari,3.0,VET,1,1,1,83.348,81.944,81.838,81.838,3,81.164,0.008304
1,2018,1,Australian Grand Prix,Mercedes,1.0,HAM,1,1,1,82.824,82.051,81.164,81.164,1,81.164,0.000000
2,2018,1,Australian Grand Prix,Ferrari,2.0,RAI,1,1,1,83.096,82.507,81.828,81.828,2,81.164,0.008181
3,2018,1,Australian Grand Prix,Red Bull Racing,8.0,RIC,1,1,1,83.494,82.897,82.152,82.152,5,81.164,0.012173
4,2018,1,Australian Grand Prix,McLaren,10.0,ALO,1,1,0,83.597,83.692,999.990,83.597,11,81.164,0.029976

(3596, 16)

In [3]:
display(f1_data.info())

display(f1_data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3596 entries, 0 to 3595
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   season                      3596 non-null   int64
 1   round                       3596 non-null   int64
 2   race_name                   3596 non-null   object
 3   team                        3596 non-null   object
 4   grid_position               3596 non-null   float64
 5   driver_code                 3596 non-null   object
 6   participated_in_qualifying  3596 non-null   int64
 7   reached_q2                  3596 non-null   int64
 8   reached_q3                  3596 non-null   int64
 9   model_q1_seconds            3596 non-null   float64
 10  model_q2_seconds            3596 non-null   float64
 11  model_q3_seconds            3596 non-null   float64
 12  best_valid_quali_time       3596 non-null   float64
 13  quali_position_numeric      3596 non-null   int64
 14  pole_time_seconds           3596 non-null   float64
 15  gap_to_pole_pct_model       3596 non-null   float64
dtypes: float64(7), int64(6), object(3)
memory usage: 449.6+ KB

None

,season,round,grid_position,participated_in_qualifying,reached_q2,reached_q3,model_q1_seconds,model_q2_seconds,model_q3_seconds,best_valid_quali_time,quali_position_numeric,pole_time_seconds,gap_to_pole_pct_model
count,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000,3596.000000
mean,2021.879588,11.033927,10.333426,0.996941,0.742214,0.493882,96.997127,325.637696,554.953717,95.562846,10.571190,82.771496,0.025492
std,2.476193,6.371788,5.841324,0.055231,0.437477,0.500032,104.654573,403.674114,457.984088,101.383619,5.837741,11.453901,0.063487
min,2018.000000,1.000000,0.000000,0.000000,0.000000,0.000000,53.904000,53.647000,53.377000,53.377000,1.000000,53.377000,-0.010590
25%,2020.000000,6.000000,5.000000,1.000000,0.000000,0.000000,76.252750,77.615500,84.462250,75.695500,6.000000,74.670000,0.007301
50%,2022.000000,11.000000,10.000000,1.000000,1.000000,0.000000,84.340500,89.783500,999.990000,83.544500,11.000000,81.299000,0.015454
75%,2024.000000,16.000000,15.000000,1.000000,1.000000,1.000000,92.958750,999.990000,999.990000,92.123500,16.000000,90.029000,0.024891
max,2026.000000,24.000000,22.000000,1.000000,1.000000,1.000000,999.990000,999.990000,999.990000,999.990000,23.000000,116.559000,0.973319

In [4]:
print(f1_data.isnull().sum())

season                        0
round                         0
race_name                     0
team                          0
grid_position                 0
driver_code                   0
participated_in_qualifying    0
reached_q2                    0
reached_q3                    0
model_q1_seconds              0
model_q2_seconds              0
model_q3_seconds              0
best_valid_quali_time         0
quali_position_numeric        0
pole_time_seconds             0
gap_to_pole_pct_model         0
dtype: int64